version: '3'
services:
  eth:
    image: mygeth:latest
    deploy:
      restart_policy:
        condition: none
      resources:
        limits:
          cpus: '1.0'
          memory: 1400M
    ports:
     - "4000"
    entrypoint: /root/start.sh
    environment:
     - SLOT={{.Task.Slot}}
    volumes:
      - ../geth/logs/:/root/logs/:rw
      - ../geth/python_scripts/:/root/python_scripts/:rw
      - ../geth/scripts/:/root/scripts/:rw
      - ../geth/contracts/:/root/contracts/:ro
      - ../geth/shared:/root/shared/:ro
      - ../geth/templates/:/root/templates/:ro
      - ../geth/files/genesis_poa.json:/root/files/genesis_poa.json:ro
      - ../geth/files/keystores:/root/.ethereum/devchain/keystores:rw
    command: '--datadir=~/.ethereum/devchain --keystore=~/.ethereum/devchain/keystores/KEYSTORE/ --gpo.percentile 0 --lightkdf --ws --ws.addr "0.0.0.0" --ws.port 8545 --ws.api "db,personal,eth,net,web3,admin,miner" --nodiscover --verbosity 0 --syncmode full --rpcapi "db,personal,eth,net,web3,admin" --allow-insecure-unlock --rpccorsdomain="*" --networkid=456719 --rpc --rpcaddr="0.0.0.0" --nat=extip:IPADDRESS'
