#!/bin/bash  

# Change to this script's folder
cd $( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )

source ../blockchainconfig

# docker stack rm ${SWARMNAME} >/dev/null 2>&1

rm -f ${DOCKERBASE}/geth/my_enode.enode

docker stack deploy -c ${DOCKERBASE}/local/docker-compose.yml ${SWARMNAME}

docker service scale ${CONTAINERBASE}=$1

docker ps -q

