#!/bin/bash  

# Change to this script's folder
cd $( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )

source ../blockchainconfig.sh

docker service scale ${CONTAINERBASE}=0

echo "Stopping containers. Maybe takes 15-20 seconds"
duration=0
while docker ps | grep -q "Up" ;
do
	let duration++
	echo -ne " ########## ($duration s) ########## \r"
	sleep 1
done

echo "Containers stopped. Removing stack"

docker service rm ${CONTAINERBASE}

docker stack rm ${SWARMNAME}



