#!/bin/bash  

docker service scale $1=0

echo "Stopping containers. Maybe takes 15-20 seconds"
duration=0
while docker ps | grep -q "Up" ;
do
	let duration++
	echo -ne " ########## ($duration s) ########## \r"
	sleep 1
done

echo "Containers stopped. Removing stack"

docker service rm $1

docker stack rm $2



