version: '3'
services:
  bootstrap:
    image: mygeth:latest
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2024M   
    hostname: bootstrap
    entrypoint: /root/start_bootstrap.sh
    command: '--datadir=~/.ethereum/devchain --keystore=~/.ethereum/devchain/keystores/KEYSTORE/ --lightkdf --ws --ws.addr "0.0.0.0" --ws.port 8545 --ws.api "db,personal,eth,net,web3,admin,miner" --nodiscover --verbosity 6 --syncmode full --rpcapi "db,personal,eth,net,web3,admin" --allow-insecure-unlock --rpccorsdomain="*" --networkid=456719 --rpc --rpcaddr="0.0.0.0" -miner.gasprice 1 --nat=extip:IPADDRESS'
    volumes:
      - ./geth/files/password:/root/files/password:ro
      - ./geth/deployed_contract:/root/deployed_contract/:rw
      - ./geth/shared:/root/shared/:rw
      - ./geth/templates/:/root/templates/:ro
      - ./geth/files/genesis.json:/root/files/genesis.json:ro
      - ./geth/files/genesis_poa.json:/root/files/genesis_poa.json:ro
      - ./geth/files/keystores:/root/.ethereum/devchain/keystores:rw  
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8555:8555"
      - "8545:8545"
  eth:
    image: mygeth:latest
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1400M 
    ports:
     - "4000"
    entrypoint: /root/start.sh
    environment:
     - SLOT={{.Task.Slot}}
    depends_on:
     - bootstrap
    volumes:
      - ./geth/files/password:/root/files/password:ro
      - ./geth/deployed_contract/:/root/deployed_contract/:ro
      - ./geth/shared:/root/shared/:ro
      - ./geth/templates/:/root/templates/:ro
      - ./geth/files/genesis.json:/root/files/genesis.json:ro
      - ./geth/files/genesis_poa.json:/root/files/genesis_poa.json:ro	
      - ./geth/files/keystores:/root/.ethereum/devchain/keystores:rw
    command: '--datadir=~/.ethereum/devchain --keystore=~/.ethereum/devchain/keystores/KEYSTORE/ --lightkdf --ws --ws.addr "0.0.0.0" --ws.port 8545 --ws.api "db,personal,eth,net,web3,admin,miner" --nodiscover --verbosity 6 --syncmode full --rpcapi "db,personal,eth,net,web3,admin" --allow-insecure-unlock --rpccorsdomain="*" --networkid=456719 --rpc --rpcaddr="0.0.0.0" -miner.gasprice 1 --nat=extip:IPADDRESS'
