#!/bin/bash

ip=`hostname -i`

echo "Starting web3 wrapper hosting"
python3 /root/python_scripts/wrapper.py&

echo "Starting peering buffer"
python3 /root/python_scripts/buffer.py&

echo "Starting analytics logging"
python3 /root/python_scripts/analytics.py $SLOT&

# echo "Starting communication size logging"
# bash /root/python_scripts/communication_size.sh $ip &


