#!/bin/bash  
# Short script to generate and upload a new genesis block
# Assumptions:
# - The Pi-puck IDs (initial sealers) are listed in pi-pucks.txt
# - puppeth is installed

parent_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

NUM_NODES=$1
CONTRACTADDRESS="0000000000000000000000000000000000000123"

if test -f "${parent_path}/genesis.conf"; then
    rm "${parent_path}/genesis.conf"
fi

########## Genesis Block Creation ############
echo "Creating a Genesis Block for $NUM_NODES nodes"
echo "+-----------------------------------------------------------+"
########## Genesis Block Creation ############


########## Genesis Configuration File ############
echo "Configuring Genesis Block..."
echo "+-----------------------------------------------------------+"
########## Genesis Configuration File ############

echo "2" >> "${parent_path}/genesis.conf"  # Manage existing genesis
echo "3" >> "${parent_path}/genesis.conf"  # Remove existing genesis
echo "2" >> "${parent_path}/genesis.conf"  # Configure new genesis
echo "1" >> "${parent_path}/genesis.conf"  # Create new genesis from scratch
echo "2" >> "${parent_path}/genesis.conf"  # Clique - proof-of-authority
echo "15" >> "${parent_path}/genesis.conf" # 15 seconds block time

# List of sealers
echo "Key Mapping"
for INDEX in $(seq 1 $NUM_NODES);
do
    KEY_FILE="$INDEX"
    KEY=$(cat "${parent_path}/keystores/$KEY_FILE/$KEY_FILE")
    echo ${KEY:12:40} >> "${parent_path}/genesis.conf"
    echo "Node $INDEX -> ${KEY:12:40}"
done
echo "" >> "${parent_path}/genesis.conf"

# pre-fund all node accounts
for INDEX in $(seq 1 $NUM_NODES);
do
    KEY_FILE="$INDEX"
    KEY=$(cat "${parent_path}/keystores/$KEY_FILE/$KEY_FILE")
    echo ${KEY:12:40} >> "${parent_path}/genesis.conf"
done

# Pre-fund the contract address
echo ${CONTRACTADDRESS} >> "${parent_path}/genesis.conf"

echo "" >> "${parent_path}/genesis.conf"

echo "yes" >> "${parent_path}/genesis.conf"  # Pre-compile addresses
echo "1515" >> "${parent_path}/genesis.conf" # Netid
echo "2" >> "${parent_path}/genesis.conf"    # Manage existing genesis 
echo "2" >> "${parent_path}/genesis.conf"    # Export genesis configurations

 # Store Genesis Configuration File
echo ${parent_path} >> "${parent_path}/genesis.conf"

########## Generate Genesis Block ############
echo "Generating Genesis Block..."
echo "+-----------------------------------------------------------+"
########## Generate Genesis Block ############

cat "${parent_path}/genesis.conf" | "${parent_path}/puppeth" --network=pipucks >/dev/null 2>&1
rm "${parent_path}/genesis.conf"

########## Upload Genesis File ############
rm "${parent_path}/genesis_poa.json"
mv "${parent_path}/pipucks.json" "${parent_path}/genesis_poa.json"
#echo "Uploading Genesis Block..."
#./scp-all /home/"$USER"/mygethnode/genesis/pipucks.json mygethnode/genesis
#wait
